// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yglfqobtcsdfvhxazwtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnbGZxb2J0Y3NkZnZoeGF6d3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODI2OTAsImV4cCI6MjA2ODA1ODY5MH0.ZagWC7sWRvCqdO4eL7ZS81b-M2dY1KAIoc-DZIB4LsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});